version: '2.2'
services:
  #User Contaienr
  user:
    container_name: user
    build: 
      context: ./user-service
      dockerfile: Dockerfile
    volumes:
      - ./user-service/static:/user/static
    env_file:
      - ./user-service/.env
    ports:
      - 8000:8000
#Post Container
  post:
    container_name: post
    build: 
      context: ./post-service
      dockerfile: Dockerfile
    volumes:
      - ./post-service/static:/post/static
    env_file:
      - ./post-service/.env
    ports:
      - 8001:8001
#Chat service
  chat:
    container_name: chat
    build: 
      context: ./chat-service
      dockerfile: Dockerfile
    volumes:
      - ./chat-service/static:/chat/static
    env_file:
      - ./chat-service/.env
    ports:
      - 8003:8003
    links:
      - redis

  redis:
    image: redis:5.0-alpine
    container_name: redis-container
    # command: redis-server
    restart: always  
    # container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - redis-network
    
  nginx:
    build: ./nginx
    volumes:
      - ./user-service/static:/user/static
      - ./post-service/static:/post/static
      - ./chat-service/static:/chat/static
      
    ports:
      - '8080:80'
    depends_on:
      - user
      - post
      - chat






volumes:
  static:

networks:
  redis-network:
    