# Generated by Django 4.2.7 on 2023-11-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_group', models.CharField(blank=True, max_length=10, null=True)),
                ('sender', models.CharField(blank=True, max_length=10, null=True)),
                ('receiver', models.CharField(blank=True, max_length=10, null=True)),
                ('content', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
